%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam;
imu: 0
num_of_cam: 2

imu_topic: "/imu/data_raw"
image0_topic: "/stereo/left/image_mono"
image1_topic: "/stereo/right/image_mono"
output_path: "/home/daybeha/Documents/github/ratslam_ws/results/VINS-Fusion/"

cam0_calib: "cam0.yaml"
cam1_calib: "cam1.yaml"
image_width: 1280
image_height: 560


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
# 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [-0.00681,-0.01532,0.99987,1.71239,
         -0.99998,0.00033,-0.00680,0.24740,
         -0.00023,-0.99988,-0.01532,-0.11589,
         0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [-0.01036,-0.01075,0.99990,1.70544,
         -0.99994,-0.00178,-0.01038,-0.22770,
         0.00189,-0.99994,-0.01073,-0.11611,
         0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 300            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

##optimization parameters
#max_solver_time: 0.08  # max solver itration time (s), to guarantee real time
#max_num_iterations: 10   # max solver itrations, to guarantee real time
#keyframe_parallax: 15   # keyframe selection threshold (pixel)

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)


##unsynchronization parameters
#estimate_td: 0                      # online estimate time offset between camera and imu
#td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

